version: 2.1
jobs:
  compile:
   docker:
      - image: ghcr.io/neutron-toolchains/docker-image:arch-neutron
   steps:
      - run:
          no_output_timeout: 50m
          command: |
           git clone https://github.com/iqbal45778/msm-4.14 kernel 
           cd kernel
           git clone https://github.com/iqbal45778/myscripts -b master
           chmod +x myscripts/clang-setup.sh
           chmod +x myscripts/mojito.sh
           source ./myscripts/clang-setup.sh
           ./myscripts/mojito.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
